name: CI pytest on GPU Google Cloud Instance

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  alias-free-gan-test:
    runs-on: ubuntu-latest

    steps:

      - name: setup google cloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: ci-test-instance | create
        run: gcloud compute instances create ci-test-instance --source-instance-template ci-test-template --zone us-central1-f

      - name: ci-test-instance | install nvidia drivers
        run: gcloud compute ssh ci-test-instance --zone us-central1-f --command "sudo /opt/deeplearning/install-driver.sh"

      - name: ci-test-instance | init anaconda
        run: gcloud compute ssh ci-test-instance --zone us-central1-f --command "/opt/conda/bin/conda init"

      - name: ci-test-instance | clone repository
        run: gcloud compute ssh ci-test-instance --zone us-central1-f --command "git clone https://github.com/duskvirkus/alias-free-gan-pytorch-lightning.git && cd alias-free-gan-pytorch-lightning && git fetch origin ${{ github.event.pull_request.head.sha }}:ci-test-branch && git checkout ci-test-branch"

      - name: ci-test-instance | pip install -r requirements.txt
        run: gcloud compute ssh ci-test-instance --zone us-central1-f --command "cd alias-free-gan-pytorch-lightning && /opt/conda/bin/pip install -r requirements.txt"

      - name: ci-test-instance | run pytest
        run: gcloud compute ssh ci-test-instance --zone us-central1-f --command "export PATH=/opt/conda/bin:$PATH && cd alias-free-gan-pytorch-lightning && python -m pytest test/unit/alias_free_gan_test.py"

      - name: ci-test-instance | stop
        if: always()
        run: gcloud compute instances stop ci-test-instance --zone us-central1-f

      - name: ci-test-instance | delete
        if: always()
        run: echo "y\n" | gcloud compute instances delete ci-test-instance --zone us-central1-f
      