name: CI pytest on GPU

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  alias-free-gan-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout code to run ci scripts
        uses: actions/checkout@v2

      - name: setup google cloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # - name: create ci-gpu-instance
      #   run: gcloud compute instances create ci-gpu-instance --source-instance-template ci-gpu-template --zone us-central1-f

      - name: create ci-gpu-instance using ci/create_gpu_instance.sh
        run: ./alias-free-gan-pytorch-lightning/ci/create_gpu_instance.sh

      - name: ci-gpu-instance | install nvidia drivers
        run: gcloud compute ssh ci-gpu-instance --zone $USING_ZONE --command "sudo /opt/deeplearning/install-driver.sh"

      - name: ci-gpu-instance | clone repository
        run: gcloud compute ssh ci-gpu-instance --zone $USING_ZONE --command "git clone https://github.com/duskvirkus/alias-free-gan-pytorch-lightning.git && cd alias-free-gan-pytorch-lightning && git fetch origin ${{ github.event.pull_request.head.sha }}:ci-gpu-branch && git checkout ci-gpu-branch"

      - name: ci-gpu-instance | install.py
        run: gcloud compute ssh ci-gpu-instance --zone $USING_ZONE --command "export PATH=/opt/conda/bin:PATH && cd alias-free-gan-pytorch-lightning && python install.py"

      - name: ci-gpu-instance | run pytest (cross and gpu tests)
        run: gcloud compute ssh ci-gpu-instance --zone $USING_ZONE --command "export PATH=/opt/conda/bin:PATH && cd alias-free-gan-pytorch-lightning && python -m pytest ./test/cross && python -m pytest ./test/gpu"

      - name: stop ci-gpu-instance
        if: always()
        run: gcloud compute instances stop ci-gpu-instance --zone $USING_ZONE

      - name: delete ci-gpu-instance
        if: always()
        run: echo "y\n" | gcloud compute instances delete ci-gpu-instance --zone $USING_ZONE
      